[package]
name = "blazing_encoders"
version = "0.1.0"
authors = ["Kirill Dubovikov <dubovikov.kirill@gmail.com>"]
edition = "2018"

[lib]
name = "blazing_encoders"
crate-type = [
"cdylib",
"rlib"
]
bench = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = "0.3.1"
assert_approx_eq = "1.1.0"

[[bench]]
name = "benchmark"
harness = false

[dependencies]
rayon = "1.3.0"
ndarray = {version = "0.13.0", features=["rayon"]}
ordered-float = "1.0.2"
numpy = "0.7.0"
pyo3 = "0.8"
num-traits = "0.2.11"
itertools = "0.8.2"
rand = "0.7.3"
#intel-mkl-sys = "0.1.0"
fnv = "1.0.2"

#[profile.dev]
#opt-level = 3
