[package]
name = "blazing-encoders"
version = "0.1.0"
authors = ["Kirill Dubovikov <dubovikov.kirill@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.3.0"
ndarray = "0.13.0"
#pyo3 = "0.8.5"
#numpy = "0.7.0"
num-traits = "0.2.11"
itertools = "0.8.2"
