name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Build
      uses: messense/maturin-action@v1
      with:
        rust-toolchain: nightly
        command: build
        target: x86_64
        manylinux: auto
        args: --release --out dist --no-sdist --compatibility manylinux2014 -i python${{ matrix.python-version }}
    - name: Run examples
      run: |
        pip install -r examples/requirements.txt
        pip install dist/*.whl
        python${{ matrix.python-version }} examples/example.py
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: dist
  
  build-macos:
    runs-on: macOS-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: python -m pip install --upgrade pip setuptools wheel
    - name: Build
      uses: messense/maturin-action@v1
      with:
        maturin-version: latest
        rust-toolchain: nightly
        command: build
        target: x86_64
        manylinux: auto
        args: --release --no-sdist -i python${{ matrix.python-version }}
    - name: Run examples
      run: |
        pip install -r examples/requirements.txt
        pip install target/wheels/*.whl
        python${{ matrix.python-version }} examples/example.py
    - name: Upload wheels
      uses: actions/upload-artifact@v2.2.4
      with:
        name: wheels
        path: ./target/wheels/*.whl
        
  release:
      name: Release
      runs-on: ubuntu-latest
      needs: [build-linux, build-macos]
      steps:
        - uses: actions/download-artifact@v2
          with:
            name: wheels
        - uses: actions/setup-python@v2
          with:
            python-version: 3.9
        - name: Publish to PyPi
          run: |
            pip install --upgrade twine
            twine upload -u ${{ secrets.MATURIN_USERNAME }} -p "${{ secrets.MATURIN_PASSWORD }}" --skip-existing *.whl
