name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.platform }}
#    container:
#      image: konstin2/maturin:master
#      volumes:
#        - .:/io
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Install Python dependencies
      run: python -m pip install --upgrade pip setuptools wheel
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        default: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build Python wheel
      run: |
        pip install -U maturin
        maturin build --release --manylinux=off --bindings=pyo3 -i python3.6
    - name: Upload wheel as artifacts
      uses: actions/upload-artifact@master
      with:
        name: wheels
        path: target/wheels/
    - name: Run examples
      run: |
        pip install -r examples/requirements.txt
        pip install target/wheels/*.whl
        python3.6 examples/example.py
