name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install Python dependencies
      run: python -m pip install --upgrade pip setuptools wheel
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build Python wheel
      run: |
        pip install -U maturin
        maturin build
    - name: Upload wheel as artifacts
        uses: actions/upload-artifact@master
        with:
          name: wheels
          path: target/wheels/
